import Icon from './Icon.svelte';

export default Icon;
export { Icon };

export const AlertTriangle = Icon;
export const Plus = Icon;
export const FileEdit = Icon;
export const Trash2 = Icon;
export const Pin = Icon;
export const PinOff = Icon;
export const MoveVertical = Icon;
export const Send = Icon;
export const Paperclip = Icon;
export const Bot = Icon;
export const User = Icon;
export const Check = Icon;
export const X = Icon;
export const Loader = Icon;
export const LayoutDashboard = Icon;
export const Building2 = Icon;
export const Palette = Icon;
export const Clock = Icon;
export const Users = Icon;
export const Megaphone = Icon;
export const Globe = Icon;
export const History = Icon;
export const UserCog = Icon;
export const Menu = Icon;
export const LogOut = Icon;
export const ChevronDown = Icon;
export const ChevronRight = Icon;
export const ChevronUp = Icon;
export const ExternalLink = Icon;
export const TriangleAlert = Icon;
export const Play = Icon;
export const GripVertical = Icon;
export const RotateCcw = Icon;
export const Lock = Icon;
export const Eye = Icon;
export const EyeOff = Icon;
