/**
 * Emits tooling/seed.ts as a plain-SQL file suitable for D1:
 *
 *   npx tsx tooling/dump-seed-sql.ts /tmp/seed.sql
 *   npx wrangler d1 execute masjid-db-staging --remote --file=/tmp/seed.sql
 *
 * Used by deploy-staging.yml to reseed the staging database on every deploy,
 * so each E2E run starts from IDENTICAL state (residue from prior runs —
 * stuck flags, leftover announcements, e2e-smoke-* masjids — is wiped).
 *
 * How it works: MASJID_DB_PATH redirects getDb()'s local SQLite path to a
 * throwaway temp file, seed.ts runs against it (self-executing module), then
 * every table is dumped as DELETE + INSERT statements in FK-safe order.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const out = process.argv[2];
if (!out) {
  console.error('Usage: npx tsx tooling/dump-seed-sql.ts <outfile.sql>');
  process.exit(2);
}

// Children-first delete order (FK-safe): every child table before its parent.
// Covers ALL schema tables — including ones the seed doesn't populate
// (posts, nav_items, config_*) — so stray rows from prior runs are removed.
const DELETE_ORDER = [
  'announcement_attachments',
  'masjid_assets',
  'config_mutations',
  'config_snapshots',
  'config_branches',
  'custom_domains',
  'prayer_rules',
  'announcements',
  'jumuah_sessions',
  'masjid_pages',
  'posts',
  'nav_items',
  'mkt_registrations',
  'mkt_outbox',
  'mkt_settings', // references mkt_terms via active_term_id — before mkt_terms
  'mkt_terms',
  'admins',
  'masjid_themes',
  'masjids',
];
// INSERT order is the exact reverse (parents first).
const INSERT_ORDER = [...DELETE_ORDER].reverse();

function sqlLiteral(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number' || typeof v === 'bigint') return String(v);
  if (Buffer.isBuffer(v) || v instanceof Uint8Array) {
    return `X'${Buffer.from(v as Uint8Array).toString('hex')}'`;
  }
  return `'${String(v).replaceAll("'", "''")}'`;
}

async function main() {
  // 1. Redirect the dev DB to a temp file, then run the seed against it.
  //    (seed.ts self-executes on import; MASJID_DB_PATH must be set first.)
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'masjid-seed-'));
  const tmpDb = path.join(tmpDir, 'seed.db');
  process.env.MASJID_DB_PATH = tmpDb;
  const { seedPromise } = await import('./seed.js');
  await seedPromise;

  // 2. Dump every table in FK-safe order.
  const { default: Database } = await import('better-sqlite3');
  const sqlite = new Database(tmpDb, { readonly: true });

  const lines: string[] = [
    '-- Auto-generated by tooling/dump-seed-sql.ts — staging reseed.',
    '-- Wipes and re-inserts every seeded table (FK-safe order).',
    '',
  ];
  for (const table of DELETE_ORDER) {
    lines.push(`DELETE FROM ${table};`);
  }
  let insertedRows = 0;
  for (const table of INSERT_ORDER) {
    const cols = (sqlite.prepare(`PRAGMA table_info(${table})`).all() as Array<{ name: string }>).map(
      (c) => c.name,
    );
    if (cols.length === 0) continue;
    const rows = sqlite.prepare(`SELECT * FROM ${table}`).all() as Array<Record<string, unknown>>;
    for (const row of rows) {
      const values = cols.map((c) => sqlLiteral(row[c])).join(', ');
      lines.push(`INSERT INTO ${table} (${cols.join(', ')}) VALUES (${values});`);
      insertedRows++;
    }
  }
  lines.push('');

  fs.writeFileSync(out, lines.join('\n'));
  console.log(`Wrote ${out}: ${DELETE_ORDER.length} DELETEs, ${insertedRows} INSERTs`);

  sqlite.close();
  fs.rmSync(tmpDir, { recursive: true, force: true });
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
